### ISSUE TITLE
[Bug Report] New update falsely applying compat mixin for a target mod that is not present

### ISSUE THREAD

**Issue by Tempest-5ky** [Bawnorton/BetterTrims#34] opened 2024-01-23 20:48 UTC
**Expected Behaviour**
Game starts as usual.

**Actual Behaviour**
Game repeatedly crashes, blaming a different mod every time the previous is removed, until BetterTrims is found as the root. Removing Bettertrims and re-enabling other blamed mods results in no crash. This seems to be because of BT breaking a major Render class, which then breaks every other mod that renders things.

**Steps to Reproduce**
- Load BetterTrims on Fabric 1.20.1, optionally with other mods
- Crash
- ...

**What version of the mod are you using**
2.1.0

**Helpful Files**
https://mclo.gs/jPHBB50 <- example of a different mod (in this case Automobility) being blamed. Scrolling down the list of respective 'caused by' entries reveals Better Trims as the true culprit on line 268 of the link.

Specific error found on line 268 of prev link: https://mclo.gs/uHDjWOJ

**Comment by Bawnorton** [comment] 2024-01-23 20:53
For some reason the mod is trying to apply it's compat mixin for iris despite iris not being present. I'll look into it

**Comment by Bawnorton** [comment] 2024-01-23 20:58
Found the cause and fixed in 2.1.1

**Closed by Bawnorton** 2024-01-23 20:58 UTC
Labels: bug
