### ISSUE TITLE
Game Crash after getting hit by Shulker's Shot

### ISSUE THREAD

**Issue by Antaner** [Bawnorton/BetterTrims#69] opened 2024-09-28 23:31 UTC
So, I've been experiencing Game crashes regularly for the last hour while being in the end. About every time I'm getting hit by a Shulker's Shot while still having the Levitation effect, the game crashes. While I'm only using Diamond Armor Trims on my full Netherite Armor, it cannot find the "user" while trying to apply some sort of Fire Aspect. Nothing I own has anything todo with fire btw. If you need more info, I'll be free to provide it.

`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-09-29 01:24:49
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_26825(net.minecraft.class_1320)" because "user" is null
	at net.minecraft.class_1890.handler$zgi000$bettertrims$applyFireAspect(class_1890.java:540)
	at net.minecraft.class_1890.method_8213(class_1890.java)
	at net.minecraft.class_1297.method_5723(class_1297.java:3100)
	at net.minecraft.class_1678.method_7454(class_1678.java:307)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1678.method_7488(class_1678.java:328)
	at net.minecraft.class_1678.method_5773(class_1678.java:238)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.mixinextras$bridge$method_31791$197(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$zgg000$bettertrims$applyElectrifying(class_3218.java:2751)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1890.handler$zgi000$bettertrims$applyFireAspect(class_1890.java:540)
	at net.minecraft.class_1890.method_8213(class_1890.java)
	at net.minecraft.class_1297.method_5723(class_1297.java:3100)
	at net.minecraft.class_1678.method_7454(class_1678.java:307)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1678.method_7488(class_1678.java:328)
	at net.minecraft.class_1678.method_5773(class_1678.java:238)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.mixinextras$bridge$method_31791$197(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$zgg000$bettertrims$applyElectrifying(class_3218.java:2751)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:shulker_bullet (net.minecraft.class_1678)
	Entity ID: 4917
	Entity Name: Shulker Bullet
	Entity's Exact location: -7596.13, 121.32, -933.22
	Entity's Block location: World: (-7597,121,-934), Section: (at 3,9,10 in -475,7,-59; chunk contains blocks -7600,0,-944 to -7585,255,-929), Region: (-15,-2; contains chunks -480,-64 to -449,-33, blocks -7680,0,-1024 to -7169,255,-513)
	Entity's Momentum: 0.00, -0.01, 0.19
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.mixinextras$bridge$method_31791$197(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$zgg000$bettertrims$applyElectrifying(class_3218.java:2751)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Antaner'/70, l='ServerLevel[Hardcore 3]', x=-7595.55, y=121.54, z=-932.44]]
	Chunk stats: 2809
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-48,96,-96), Section: (at 0,0,0 in -3,6,-6; chunk contains blocks -48,0,-96 to -33,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3647069 game time, 5055073 day time
	Level name: Hardcore 3
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
	Level weather: Rain time: 7359 (now: false), thunder time: 7785 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1075265096 bytes (1025 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x164e
	Graphics card #0 versionInfo: DriverVersion=32.0.11024.2
	Graphics card #1 name: NVIDIA GeForce RTX 4060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2882
	Graphics card #1 versionInfo: DriverVersion=32.0.15.5612
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 6.00
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 6.00
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 34453.89
	Virtual memory used (MB): 22790.59
	Swap memory total (MB): 2560.00
	Swap memory used (MB): 191.54
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		allthetrims: AllTheTrims 3.4.3
		architectury: Architectury 9.2.14
		autocraft: Autocrafting Table Mod 1.0.4
			libgui: LibGui 8.1.0+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		beaconoverhaul: Beacon Overhaul 1.8.4+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		betterf3: BetterF3 7.0.2
			cloth-config: Cloth Config v11 11.1.106
				cloth-basic-math: cloth-basic-math 0.6.1
		betterstats: Better Statistics Screen 3.12.6+fabric-1.20.1
		betterthanmending: BetterThanMending 1.3.0
		bettertrims: BetterTrims 3.1.3
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
		chunksfadein: Chunks Fade In 1.0.7-1.20.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		citresewn: CIT Resewn 1.1.5+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.1.5+1.20.1
		configurable: Configurable 1.3.0
		cupboard: cupboard 1.20.1-2.7
		easyanvils: Easy Anvils 8.0.2
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.2
			puzzlesapi: Puzzles Api 8.1.6
				cardinal-components-base: Cardinal Components API (base) 5.2.2
				cardinal-components-entity: Cardinal Components API (entities) 5.2.2
				puzzlesaccessapi: Puzzles Access Api 8.0.9
		elytratrims: Elytra Trims 3.5.1
			conditional-mixin: conditional mixin 0.6.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		explorify: Explorify 1.6.2
		explosiveenhancement: Explosive Enhancement 1.2.2-1.20.x
		exposure: Exposure 1.7.7
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		freecam: Freecam 1.2.1+1.20
		geophilic: Geophilic 3.1.3
		indium: Indium 1.0.34+mc1.20.1
		inventorio: Inventorio 1.10.3
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.19.5.99
		leavesbegone: Leaves Be Gone 8.0.0
		minecraft: Minecraft 1.20.1
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 7.2.2
		notenoughanimations: NotEnoughAnimations 1.7.6
		puzzleslib: Puzzles Lib 8.1.23
		replaymod: Replay Mod 1.20.1-2.6.19
		resourcepackoverrides: Resource Pack Overrides 8.0.3
		satin: Satin 1.14.0
		sodium: Sodium 0.5.11+mc1.20.1
		stackablepotions: Stackable Potions 1.0.0
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		tcdcommons: TCD Commons API 3.12.3+fabric-1.20.1
		visuality: Visuality 0.7.1+1.20
		wakes: Wakes 0.3.0+1.20.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.20.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Loaded Shaderpack: ComplementaryShaders_v4.7.1.zip
		Profile: Custom (+30 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Antaner'/70, l='ServerLevel[Hardcore 3]', x=-7595.55, y=121.54, z=-932.44]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.5-1.20.1`

**Comment by Antaner** [comment] 2024-09-28 23:39
maybe it's nothin todo with me per-say, since I just didnt get hit, but the same crash occurred. Maybe two entities hitting each other, but idk

**Comment by Bawnorton** [comment] 2024-09-28 23:42
Found the cause, will be fixed in the next release

**Comment by Antaner** [comment] 2024-09-28 23:49
thank you very much for the insanely fast response and the fix lol

**Comment by Bawnorton** [comment] 2024-09-28 23:51
Gonna leave open until the next release is published, should be tmrw or monday

**Comment by Bawnorton** [comment] 2024-09-30 05:13
Should be fixed in latest release

**Closed by Bawnorton** 2024-09-30 05:13 UTC
