### ISSUE TITLE
Error while loading mods on Neoforge (1.21.1)

### ISSUE THREAD

**Issue by TheNoirVoid** [Bawnorton/BetterTrims#72] opened 2024-10-03 17:36 UTC
It's say:

![image](https://github.com/user-attachments/assets/437b8341-2ee3-4f31-b2a0-682fac0b306b)

Which is confusing because I use neoforge but I need to download the fabric API is that even possible?
And also the another "YetAnotherConfigLib" mod is also not updated in 1.21.1 yet. Can the old one be use for this?

**Comment by Bawnorton** [comment] 2024-10-03 17:38
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

Yes. 1.21 and 1.21.1 are for all intents and purposes identical.

**Comment by TheNoirVoid** [comment] 2024-10-03 17:48
Okay Now I downloaded the Fabric API mod you sent the link here (Thank you btw. I didn't even know that kind of mod existed)
But now looks like my game is crashing with the "YetAnotherConfigLib" mod idk why. Is it's because it's out of version? or it's just messed up with some other mod I have?
![image](https://github.com/user-attachments/assets/90ee9fa4-0a51-4111-8315-6af996dc5343)

**Comment by Bawnorton** [comment] 2024-10-03 17:49
Send the crash report

**Comment by TheNoirVoid** [comment] 2024-10-03 17:51
Here
[Uploading crash-2024-10-04_00.51.24-client.txt…]()

**Comment by Bawnorton** [comment] 2024-10-03 17:53
you need to wait for it to finish uploading before sending

**Comment by Bawnorton** [comment] 2024-10-03 17:58
Hmm, something is conflicting with BetterTrims. Unsure what

**Comment by Bawnorton** [comment] 2024-10-03 18:14
Found the cause, fixed in 3.2.3 which will be published shortly

**Closed by Bawnorton** 2024-10-03 18:14 UTC

**Comment by TheNoirVoid** [comment] 2024-10-03 18:36
Thanks for your work. Keep it up
