### ISSUE TITLE
[Bug Report] Incompatible with create fabric mod

### ISSUE THREAD

**Issue by gqrshy** [Bawnorton/BetterTrims#50] opened 2024-04-14 07:34 UTC
**Expected Behaviour**
Summary of what should have happened

**Actual Behaviour**
Summary of what actually happened

**Steps to Reproduce**
- Step 1
- Step 2
- ...

**What version of the mod are you using**
beter trims 2.3.0*(latest)
create fabric mod  -  Create 1.20.1 v0.5.1.f Patch 1*(latest)

**Helpful Files**
Drag and drop these files here to help me figure out what broke.
[crash-2024-04-14_16.24.17-client.txt](https://github.com/Bawnorton/BetterTrims/files/14969852/crash-2024-04-14_16.24.17-client.txt)

- latest.log
  - Found in `.minecraft/logs`
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14969853/latest.log)
![image](https://github.com/Bawnorton/BetterTrims/assets/88965460/8e80864e-c40d-466a-a256-7a9250763333)

**Comment by Bawnorton** [comment] 2024-04-14 15:49
Duplicate of #47, the mod resolution is not accurate

**Closed by Bawnorton** 2024-04-14 15:49 UTC
Labels: bug
